import type { PatchRequest } from '../src/types';

/**
 * Fixture demonstrates a PatchRequest generated by the repair writer
 * to address two issues from the verification report:
 *
 *   issue_v001 (terminology_drift) → replace_span: "step function" → "step-based workflow"
 *   issue_v002 (unsupported_claim) → delete_span: remove the untraced cold-start sentence
 *
 * Both ops are span_patch strategy — the smallest available scope.
 */
export const patchRequestFixture: PatchRequest = {
  runId: 'run_a1b2c3d4e5f6',
  draftVersion: 1,
  issueIds: ['issue_v001', 'issue_v002'],
  rationale:
    'Fixing two error-severity verification issues: a terminology mismatch and an untraced claim. Both are span-level fixes that do not require rewriting surrounding paragraphs.',
  requestedBy: 'repair_writer',
  createdAt: '2026-04-17T10:20:00.000Z',
  ops: [
    {
      type: 'replace_span',
      sectionId: 'orchestration_model',
      spanId: 'span_orch_para2_s3',
      newContent: 'step-based workflow',
    },
    {
      type: 'delete_span',
      sectionId: 'developer_implications',
      spanId: 'span_devimpl_para3_s1',
    },
  ],
};
